version: '3.5'
services:
  # databases_test:
  #     image: mysql
  #     ports:
  #     - "3307:3306"
  #     environment:
  #     - MYSQL_ROOT_PASSWORD=password
  #     - MYSQL_USER=user
  #     - MYSQL_PASSWORD=password
  #     - MYSQL_DATABASE=password
  web:
    build: .
    container_name: simple-app
    volumes:
      - "simple-web:/var/www/html"
    ports:
      - "8888:80"

volumes:
  simple-web:
